version: '3'
services:
  raytracing_sim:
    build: .
    container_name: raytracing_sim
    volumes:
      - .:/usr/src/app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
